### PR TITLE
Rewind request body

### PR DESCRIPTION
**Pull request by mrceperka**
Request body is empty in subsequent middlewares, because it was not rewound.

#### Checklist
- [x] Pull request contains a clear definition of changes
- [x] Tests (either unit, integration, or acceptance) written and passing
- [x] Relevant documentation produced and/or updated

### CODE REVIEW

**Comment by chadicus** [comment]
@mrceperka  can you please add a unit test which shows the unwanted behavior?

**Comment by mrceperka** [comment]
Hi @chadicus, thanks for response. I will try to add some unit tests this week...

**Comment by mrceperka** [comment]
@chadicus It would be great if u could also release https://github.com/chadicus/slim-oauth2 with this fix applied.

**Comment by chadicus** [comment]
Merged with #40

**Comment by chadicus** [comment]
Thanks for the contribution!

**Pull request closed without merging**
